on:
  push:

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3.3.1
        with:
          args: "--out-${NO_FUTURE}format colored-line-number"
