on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Unit Tests
      run: go test -v ./...

    - name: Generate Coverage Report
      run: |
        go test -json -coverprofile=cover.out ./... > result.json
        go tool cover -func cover.out

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
