on:
  workflow_dispatch:
  schedule:
   - cron: "0 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - uses: champ-oss/file-sync@v1.0.42-59b6524
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          repo: champ-oss/terraform-module-template
          files: |
            .gitignore
            LICENSE
            .tflint.hcl
            .github/CODEOWNERS
            .github/workflows/release.yml