name: sync

on:
  workflow_dispatch:
  schedule:
   - cron: "0 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - uses: champ-oss/file-sync@v1.0.41-5e961bb
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          repo: champ-oss/terraform-module-template
          files: |
            .gitignore
            LICENSE
            .tflint.hcl
            .github/CODEOWNERS
            .github/dependabot.yml
            .github/workflows/lint.yml
            .github/workflows/release.yml
            examples/complete/.terraform.lock.hcl=.terraform.lock.hcl
