name: update-terraform-lockfile

on:
  workflow_dispatch:
  push:
  schedule:
   - cron: "0 4 * * *"

jobs:
  root-folder:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false
      - uses: champ-oss/update-terraform-lockfile@66c4fb7ace109a11aab137fa17fc820c3ae19ce8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test-folder:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false
      - uses: champ-oss/update-terraform-lockfile@66c4fb7ace109a11aab137fa17fc820c3ae19ce8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: test
