on:
  workflow_dispatch:
  push:
  schedule:
   - cron: "0 4 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.1.4
          terraform_wrapper: false
      - uses: champ-oss/update-terraform-lockfile@e9d76db17ee9e148d4d13658ca12e6930dd81094
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
